# Generated by Django 2.2.2 on 2019-06-18 06:17

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_image', models.CharField(max_length=200)),
                ('owner_phone_number', phone_field.models.PhoneField(max_length=31)),
                ('owner_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rover_app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_name', models.CharField(max_length=50)),
                ('sitter_image', models.CharField(max_length=200)),
                ('sitter_phone_number', phone_field.models.PhoneField(max_length=31)),
                ('sitter_email', models.CharField(max_length=100)),
                ('sitter_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_rating_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_sitter_rank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('text', models.TextField(max_length=1000)),
                ('start_date', models.DateField(max_length=50)),
                ('end_date', models.DateField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rover_app.Owner')),
                ('pets', models.ManyToManyField(to='rover_app.Pet', verbose_name='List of Pets')),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rover_app.Sitter')),
            ],
        ),
    ]
